from NekoRobot import (
    DEV_USERS,
    SUDO_USERS,
    SUPPORT_USERS,
    TIGERS,
    WHITELIST_USERS,
    tbot,
)

IMMUNE_USERS = SUDO_USERS + WHITELIST_USERS + SUPPORT_USERS + TIGERS + DEV_USERS

IMMUNE_USERS = (
    list(SUDO_USERS)
    + list(WHITELIST_USERS)
    + list(SUPPORT_USERS)
    + list(TIGERS)
    + list(DEV_USERS)
)
